[project]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "parallel_Lee"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0,<25"
